[build]
    publish = "public"
    functions = "functions"
      
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/src/static/fonts/jost-400.woff2"
  [headers.value]
    Access-Control-Allow-Origin = "https://js.stripe.com"