[build]
    publish = "public"
    functions = "functions"
      
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/fonts/jost-400.woff2"
    [headers.value]
      Access-Control-Allow-Origin = "https://js.stripe.com"
      Content-Type = "application/font-woff2"
      Cache-Control = "public, max-age=31536000"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"