[build]
    publish = "public"
    functions = "functions"
      
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/fonts/jost-400.woff2"
  [headers.value]
    Access-Control-Allow-Origin = "https://js.stripe.com"

[[headers]]
  for = "/*"
  [headers.value]
    Content-Security-Policy = "default-src self; connect-src https://api.stripe.com; frame-src https://js.stripe.com https://hooks.stripe.com; script-src https://js.stripe.com;"
